// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6zAgFO3c4ElsasfPDlpJVxDh4nIkUZI',
    appId: '1:1065930565221:web:b94955c8873a1ab49fc88c',
    messagingSenderId: '1065930565221',
    projectId: 'flutter-app-distribution-2ea5d',
    authDomain: 'flutter-app-distribution-2ea5d.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-2ea5d.firebasestorage.app',
    measurementId: 'G-PS3PS7YN3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpER8ElRd3ZLiYy6a66PX24Ba-uusPDt4',
    appId: '1:1065930565221:android:72f5fa3c77f905199fc88c',
    messagingSenderId: '1065930565221',
    projectId: 'flutter-app-distribution-2ea5d',
    storageBucket: 'flutter-app-distribution-2ea5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn7KYe-MwgN-RBobLx6aFOyJGRb6ABHjI',
    appId: '1:1065930565221:ios:ca3cd01143ca87ea9fc88c',
    messagingSenderId: '1065930565221',
    projectId: 'flutter-app-distribution-2ea5d',
    storageBucket: 'flutter-app-distribution-2ea5d.firebasestorage.app',
    iosClientId: '1065930565221-epb81k4dktnucig1mi3lip9oekvbfj5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn7KYe-MwgN-RBobLx6aFOyJGRb6ABHjI',
    appId: '1:1065930565221:ios:ca3cd01143ca87ea9fc88c',
    messagingSenderId: '1065930565221',
    projectId: 'flutter-app-distribution-2ea5d',
    storageBucket: 'flutter-app-distribution-2ea5d.firebasestorage.app',
    iosClientId: '1065930565221-epb81k4dktnucig1mi3lip9oekvbfj5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT6zAgFO3c4ElsasfPDlpJVxDh4nIkUZI',
    appId: '1:1065930565221:web:7a6702944b30dfa89fc88c',
    messagingSenderId: '1065930565221',
    projectId: 'flutter-app-distribution-2ea5d',
    authDomain: 'flutter-app-distribution-2ea5d.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-2ea5d.firebasestorage.app',
    measurementId: 'G-MTX40H4MWV',
  );
}
